ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"

default_platform(:ios)

desc "Build for testing"
  lane :build_for_testing do
    run_tests(
      derived_data_path: "build_derived_data_folder",
      build_for_testing: true
    )
  end

desc "Run tests"
  lane :run_tests_from_build do
    run_tests(
      derived_data_path: "build_derived_data_folder",
      test_without_building: true
    )
  end

desc "Build and test"
  lane :build_and_test do
    build_for_testing
    run_tests_from_build
  end