ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"

default_platform(:ios)

desc "Build for testing"
  lane :build_for_testing do
    run_tests(
      derived_data_path: "build_derived_data_folder",
      build_for_testing: true,
      device: "iPhone 8 Plus",
      prelaunch_simulator: true
    )
  end

desc "Run tests"
  lane :run_tests_from_build do
    run_tests(
      derived_data_path: "build_derived_data_folder",
      test_without_building: true,
      device: "iPhone 8 Plus",
      prelaunch_simulator: true
    )
  end

desc "Build and test"
  lane :build_and_test do
    build_for_testing
    run_tests_from_build
    slack(message: "✅ App was successfully built and tested") 
  end

error do |lane, exception|
  slack(message: "❌ Lane #{lane} FAILED!",
	success: false,
	attachment_properties: {
           fields: [
               {
                   title: "Error message",
                   value: exception.to_s,
                   short: false
               },
		{
		   title: "Build URL",
		   value: ENV['BUILD_URL'],
		   short: false
		}
           ]
       })
end