name: Build and Test

env:
    BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.8
        bundler-cache: true
    - name: Run
      env:
        SLACK_URL: ${{ secrets.SLACK_URL }}
      run: bundle exec fastlane build_and_test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: diff-screenshots
        path: AvitoInternship2022UITests/FailureDiffs/AvitoInternship2022UITests.EmployeesScreenUITests/*.png
